(*
This file is generated by Cogent

*)

theory Nested_boxed_dargentisa_CorresSetup_Edited
imports "CogentCRefinement.Deep_Embedding_Auto"
"CogentCRefinement.Cogent_Corres"
"CogentCRefinement.Tidy"
"CogentCRefinement.Heap_Relation_Generation"
"CogentCRefinement.Type_Relation_Generation"
"CogentCRefinement.Dargent_Custom_Get_Set"
"build_nested_boxed/Nested_boxed_dargentisa_ACInstall"
"build_nested_boxed/Nested_boxed_dargentisa_TypeProof"
"../Complements"
begin

(* C type and value relations *)

instantiation unit_t_C :: cogent_C_val
begin
  definition type_rel_unit_t_C_def: "\<And> r. type_rel r (_ :: unit_t_C itself) \<equiv> r = RUnit"
  definition val_rel_unit_t_C_def: "\<And> uv. val_rel uv (_ :: unit_t_C) \<equiv> uv = UUnit"
  instance ..
end

instantiation bool_t_C :: cogent_C_val
begin
definition type_rel_bool_t_C_def: "\<And> typ. type_rel typ (_ :: bool_t_C itself) \<equiv> (typ = RPrim Bool)"
definition val_rel_bool_t_C_def:
   "\<And> uv x. val_rel uv (x :: bool_t_C) \<equiv> (boolean_C x = 0 \<or> boolean_C x = 1) \<and>
     uv = UPrim (LBool (boolean_C x \<noteq> 0))"
instance ..
end
context update_sem_init begin
lemmas corres_if = corres_if_base[where bool_val' = boolean_C,
                     OF _ _ val_rel_bool_t_C_def[THEN meta_eq_to_obj_eq, THEN iffD1]]
end
(* C heap type class *)
class cogent_C_heap = cogent_C_val +
  fixes is_valid    :: "lifted_globals \<Rightarrow> 'a ptr \<Rightarrow> bool"
  fixes heap        :: "lifted_globals \<Rightarrow> 'a ptr \<Rightarrow> 'a"

(*
Non-generated
*)



(* TODO: move this lemma in the C-parser library, where t1_C_updupd_same
is generated (c-parser/recursive_records/recursive_record_package.ML),
or pass them as an argument to generate_isa_getset
*)

(*
lemma heap_t1_C_update_comp[simp]:
  " heap_t1_C_update f o heap_t1_C_update f' = heap_t1_C_update (f o f')"
  by fastforce

lemma heap_t1_C_update_if[simp] : "
(if b then heap_t1_C_update f z else heap_t1_C_update g z) = 
  heap_t1_C_update (\<lambda> x. if b then f x else g x) z"
  by fastforce

lemma heap_t2_C_update_comp[simp]:
  " heap_t2_C_update f o heap_t2_C_update f' = heap_t2_C_update (f o f')"
  by fastforce

lemma heap_t2_C_update_if[simp] : "(if b then heap_t2_C_update f z else heap_t2_C_update g z) = 
  heap_t2_C_update (\<lambda> x. if b then f x else g x) z"
  by simp
*)



(* 
This ML function generate custom getters/setters in Isabelle from
the C custom getters/setters.

More precisely, the involved steps are:
1. get the names of custom C getters/setters from the table file
2. prove a simplified definition of them by unfolding the auxiliary 
   called C functions and using Tidy lemmas (thus produces Cgetter_def' 
   lemmas in the context). 
3. infer an isabelle definition of custom getter/setters by inspecting
   these simplified definition (and performing further simplification, such
   as removing all guards)

The simplified definitions are thought to be used later when proving that
the C and isabelle custom getters/setters match.

 *)


find_theorems name:get_aa
setup \<open>generate_isa_getset_records_for_file "nested_boxed_dargentisa.c" @{locale nested_boxed_dargentisa} \<close>

context nested_boxed_dargentisa begin


(* Example: 
 1 original C getter definition, 
 2 simplified unfolded definition
 3 isabelle C getter definition
*)
thm d3_get_aa'_def d3_get_aa'_def' deref_d3_get_aa_def
term deref_d3_get_aa

end
(* the value/type relation were adapted to custom layouts *)


context nested_boxed_dargentisa begin
end
(* end of non-generated *)

local_setup \<open> local_setup_val_rel_type_rel_put_them_in_buckets "nested_boxed_dargentisa.c" \<close>
local_setup \<open> local_setup_instantiate_cogent_C_heaps_store_them_in_buckets "nested_boxed_dargentisa.c" \<close>
locale Nested_boxed_dargentisa = "nested_boxed_dargentisa" + update_sem_init
begin

(*



 *)

(* This prints the get/set lemmas that should be proven *)
ML \<open> val lems = mk_getset_lems "nested_boxed_dargentisa.c" @{context} \<close>
ML \<open>lems  |> map (string_of_getset_lem @{context})|> map tracing\<close>





thm L2opt
lemma d3_get_aa_def_alt[GetSetSimp] : "d3_get_aa' ptr = do _ <- guard (\<lambda>s. is_valid_t2_C s ptr);
                                                           gets (\<lambda>s. deref_d3_get_aa (heap_t2_C s ptr))
                                                        od"
  by (tactic \<open>custom_get_set_monadic_direct_tac @{context} 1\<close>)

lemma t2_C_get_aa_set_aa[GetSetSimp] : "val_rel x v \<Longrightarrow> val_rel x (deref_d3_get_aa (deref_d9_set_aa b v))"

  apply(simp add:GetSetDefs)
  by (tactic \<open>getput_variant_tac @{context} []\<close>)


lemma d9_set_aa_def_alt[GetSetSimp] : "d9_set_aa' ptr v =
                                       do _ <- guard (\<lambda>s. is_valid_t2_C s ptr);
                                          modify (heap_t2_C_update (\<lambda>a. a(ptr := deref_d9_set_aa (a ptr) v)))
                                       od"
by (tactic \<open>custom_get_set_monadic_direct_tac @{context} 1\<close>)


(* Relation between program heaps *)
definition
  heap_rel_ptr ::
  "(funtyp, abstyp, ptrtyp) store \<Rightarrow> lifted_globals \<Rightarrow>
   ('a :: cogent_C_heap) ptr \<Rightarrow> bool"
where
  "\<And> \<sigma> h p.
    heap_rel_ptr \<sigma> h p \<equiv>
   (\<forall> uv.
     \<sigma> (ptr_val p) = Some uv \<longrightarrow>
     type_rel (uval_repr uv) TYPE('a) \<longrightarrow>
     is_valid h p \<and> val_rel uv (heap h p))"

lemma heap_rel_ptr_meta:
  "heap_rel_ptr = heap_rel_meta is_valid heap"
  by (simp add: heap_rel_ptr_def[abs_def] heap_rel_meta_def[abs_def])

local_setup \<open> local_setup_heap_rel "nested_boxed_dargentisa.c" \<close>

definition state_rel :: "((funtyp, abstyp, ptrtyp) store \<times> lifted_globals) set"
where
  "state_rel  = {(\<sigma>, h). heap_rel \<sigma> h}"

lemmas val_rel_simps[ValRelSimp] =
  val_rel_word
  val_rel_ptr_def
  val_rel_unit_def
  val_rel_unit_t_C_def
  val_rel_bool_t_C_def
  val_rel_fun_tag

lemmas type_rel_simps[TypeRelSimp] =
  type_rel_word
  type_rel_ptr_def
  type_rel_unit_def
  type_rel_unit_t_C_def
  type_rel_bool_t_C_def



(* Generating the specialised take and put lemmas *)

local_setup \<open> local_setup_take_put_member_case_esac_specialised_lemmas "nested_boxed_dargentisa.c" \<close>
local_setup \<open> fold tidy_C_fun_def' Cogent_functions \<close>

end (* of locale *)


end
