// This file is generated by Cogent

#include "random_seed_master.h"

static inline t1 main(Seed *a1)
{
    Seed *r2 = a1;
    t1 r3 = rand_with_seed(r2);
    Seed *r4 = r3.seed;
    t1 r5 = rand_with_seed(r4);
    Seed *r6 = r5.seed;
    u8 r7 = r3.value;
    u8 r8 = r5.value;
    u8 r9 = (u8) ((u32) r7 + (u32) r8);
    t1 r10 = (t1) {.seed = r6, .value = r9};
    
    return r10;
}


