(*
This file is generated by Cogent

*)

theory Random_seed_NormalProof
imports "CogentShallow.Shallow_Normalisation_Tac"
"Random_seed_Shallow_Desugar"
"Random_seed_Shallow_Normal"
begin

ML \<open>
val Cogent_functions = ["main"]
\<close>

ML \<open>
val normalisation_thms = normalisation_tac_all @{context} "Random_seed_Shallow_Desugar" "Random_seed_Shallow_Normal" [] [] Cogent_functions
\<close>


end
