// This file is generated by Cogent

#ifndef RANDOM_SEED_H__
#define RANDOM_SEED_H__

#include <cogent-defns.h>
#include <cogent-endianness.h>

enum {
    LET_TRUE = 1,
} ;
enum {
    LETBANG_TRUE = 1,
} ;
enum untyped_func_enum {
    FUN_ENUM_main,
    FUN_ENUM_rand_with_seed,
} ;
typedef enum untyped_func_enum untyped_func_enum;
typedef untyped_func_enum t2;
#define FUN_DISP_MACRO_dispatch_t2(a1, a2, a3)\
{\
    {\
        switch (a2) {\
            \
          case FUN_ENUM_main:\
            {\
                a1 = main(a3);\
                break;\
            }\
            \
          default:\
            {\
                a1 = rand_with_seed(a3);\
                break;\
            }\
        }\
    }\
}
typedef struct t1 t1;
struct t1 {
    Seed *seed;
    u8 value;
} ;
static inline t1 rand_with_seed(Seed *);
static inline t1 main(Seed *);
static inline t1 dispatch_t2(untyped_func_enum a2, Seed *a3)
{
    switch (a2) {
        
      case FUN_ENUM_main:
        return main(a3);
        
      default:
        return rand_with_seed(a3);
    }
}
typedef t1 SeedValue;
typedef Seed *main_arg;
typedef t1 main_ret;
typedef Seed *rand_with_seed_arg;
typedef t1 rand_with_seed_ret;
#endif


