/*
This file is generated by Cogent

*/

typedef struct Seed {
            int dummy;
        } Seed;
typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;
typedef unsigned long long u64;
typedef struct unit_t {
            int dummy;
        } unit_t;
typedef struct bool_t {
            u8 boolean;
        } bool_t;
const int ENDIANNESS_TEST = 1;
static inline u16 swap_u16(u16 v)
{
    return v << 8 | v >> 8;
}
static inline u32 swap_u32(u32 v)
{
    v = (v << 8 & 0xFF00FF00) | (v >> 8 & 0xFF00FF);
    return v << 16 | v >> 16;
}
static inline u64 swap_u64(u64 v)
{
    v = (v << 8 & 0xFF00FF00FF00FF00) | (v >> 8 & 0x00FF00FF00FF00FF);
    v = (v << 16 & 0xFFFF0000FFFF0000) | (v >> 16 & 0x0000FFFF0000FFFF);
    return v << 32 | v >> 32;
}
static inline u8 be_u8_swap(u8 v)
{
    return v;
}
static inline u16 be_u16_swap(u16 v)
{
    return *(char *) &ENDIANNESS_TEST == 0 ? v : swap_u16(v);
}
static inline u32 be_u32_swap(u32 v)
{
    return *(char *) &ENDIANNESS_TEST == 0 ? v : swap_u32(v);
}
static inline u64 be_u64_swap(u64 v)
{
    return *(char *) &ENDIANNESS_TEST == 0 ? v : swap_u64(v);
}
static inline u8 le_u8_swap(u8 v)
{
    return v;
}
static inline u16 le_u16_swap(u16 v)
{
    return *(char *) &ENDIANNESS_TEST == 0 ? swap_u16(v) : v;
}
static inline u32 le_u32_swap(u32 v)
{
    return *(char *) &ENDIANNESS_TEST == 0 ? swap_u32(v) : v;
}
static inline u64 le_u64_swap(u64 v)
{
    return *(char *) &ENDIANNESS_TEST == 0 ? swap_u64(v) : v;
}
enum {
    LET_TRUE = 1,
} ;
enum {
    LETBANG_TRUE = 1,
} ;
enum untyped_func_enum {
    FUN_ENUM_main,
    FUN_ENUM_rand_with_seed,
} ;
typedef enum untyped_func_enum untyped_func_enum;
typedef untyped_func_enum t2;
typedef struct t1 t1;
struct t1 {
    Seed *seed;
    u8 value;
} ;
static inline t1 rand_with_seed(Seed *);
static inline t1 main(Seed *);
static inline t1 dispatch_t2(untyped_func_enum a2, Seed *a3)
{
    switch (a2) {
        
      case FUN_ENUM_main:
        return main(a3);
        
      default:
        return rand_with_seed(a3);
    }
}
typedef t1 SeedValue;
typedef Seed *main_arg;
typedef t1 main_ret;
typedef Seed *rand_with_seed_arg;
typedef t1 rand_with_seed_ret;
static inline t1 main(Seed *a1)
{
    Seed *r2 = a1;
    t1 r3 = rand_with_seed(r2);
    Seed *r4 = r3.seed;
    t1 r5 = rand_with_seed(r4);
    Seed *r6 = r5.seed;
    u8 r7 = r3.value;
    u8 r8 = r5.value;
    u8 r9 = (u8) ((u32) r7 + (u32) r8);
    t1 r10 = (t1) {.seed = r6, .value = r9};
    
    return r10;
}
char rand();
SeedValue rand_with_seed(Seed *s)
{
    SeedValue r = {.seed =s, .value =rand()};
    
    return r;
}


