(*
This file is generated by Cogent
*)
theory Random_seed_master_ACInstall
imports
  "AutoCorres.AutoCorres"

begin


declare [[record_codegen = false]]
declare [[use_anonymous_local_variables=true]]
new_C_include_dir "Cogent.lib"
install_C_file "random_seed_master_pp_inferred.c"
autocorres [keep_going, ts_rules = nondet, no_opt, skip_word_abs] 
      "random_seed_master_pp_inferred.c"

end

