(*
This file is generated by Cogent

*)

theory U8rec_uabsfunsdeclfix_NormalProof
imports "CogentShallow.Shallow_Normalisation_Tac"
"U8rec_uabsfunsdeclfix_Shallow_Desugar"
"U8rec_uabsfunsdeclfix_Shallow_Normal"
begin

ML \<open>
val Cogent_functions = ["main"]
\<close>

ML \<open>
val normalisation_thms = normalisation_tac_all @{context} "U8rec_uabsfunsdeclfix_Shallow_Desugar" "U8rec_uabsfunsdeclfix_Shallow_Normal" [] [] Cogent_functions
\<close>


end
