(*
This file is generated by Cogent

*)

theory U8rec_uabsfunsdeclfix_Shallow_Desugar_Tuples
imports "U8rec_uabsfunsdeclfix_ShallowShared_Tuples"
begin

definition
  main :: "8 word T0 \<Rightarrow> 8 word T0"
where
  "main ds\<^sub>0 \<equiv>
    ds\<^sub>0"

end
