(*
This file is generated by Cogent

*)

theory U8rec_uabsfunsdeclfix_Shallow_Normal
imports "U8rec_uabsfunsdeclfix_ShallowShared"
begin

definition
  main :: "8 word T0 \<Rightarrow> 8 word T0"
where
  "main ds\<^sub>0 \<equiv> HOL.Let ds\<^sub>0 (\<lambda>x. x)"

end
