// This file is generated by Cogent

#ifndef U8REC_UABSFUNSDECLFIX_H__
#define U8REC_UABSFUNSDECLFIX_H__

#include <cogent-defns.h>
#include <cogent-endianness.h>

enum {
    LET_TRUE = 1,
} ;
enum {
    LETBANG_TRUE = 1,
} ;
enum untyped_func_enum {
    FUN_ENUM_main,
} ;
typedef enum untyped_func_enum untyped_func_enum;
typedef untyped_func_enum t2;
#define FUN_DISP_MACRO_dispatch_t2(a1, a2, a3)\
{\
    {\
        a1 = main(a3);\
    }\
}
typedef struct t1 t1;
struct t1 {
    u8 a;
} ;
static inline t1 *main(t1 *);
static inline t1 *dispatch_t2(untyped_func_enum a2, t1 *a3)
{
    return main(a3);
}
typedef t1 *main_arg;
typedef t1 *main_ret;
#endif


