(*
This file is generated by Cogent
*)
theory ParseC
imports
  "AutoCorres.AutoCorres"

begin


declare [[record_codegen = false]]
declare [[use_anonymous_local_variables=true]]
new_C_include_dir "/home/laf027/cogent/branches/arrayverif/cogent/lib"






install_C_file "meson_timer.c"
autocorres [keep_going, ts_rules = nondet, no_opt, skip_word_abs, skip_heap_abs] "meson_timer.c"


end

