(*
This file is generated by Cogent

*)

theory Onefield_bits_dargentisa_CorresSetup_Edited
imports "CogentCRefinement.Deep_Embedding_Auto"
"CogentCRefinement.Cogent_Corres"
"CogentCRefinement.Tidy"
"CogentCRefinement.Heap_Relation_Generation"
"CogentCRefinement.Type_Relation_Generation"

"build_onefield_bits/Onefield_bits_dargentisa_ACInstall"
"build_onefield_bits/Onefield_bits_dargentisa_TypeProof"
"../Complements"
begin

(* C type and value relations *)

instantiation unit_t_C :: cogent_C_val
begin
  definition type_rel_unit_t_C_def: "\<And> r. type_rel r (_ :: unit_t_C itself) \<equiv> r = RUnit"
  definition val_rel_unit_t_C_def: "\<And> uv. val_rel uv (_ :: unit_t_C) \<equiv> uv = UUnit"
  instance ..
end

instantiation bool_t_C :: cogent_C_val
begin
definition type_rel_bool_t_C_def: "\<And> typ. type_rel typ (_ :: bool_t_C itself) \<equiv> (typ = RPrim Bool)"
definition val_rel_bool_t_C_def:
   "\<And> uv x. val_rel uv (x :: bool_t_C) \<equiv> (boolean_C x = 0 \<or> boolean_C x = 1) \<and>
     uv = UPrim (LBool (boolean_C x \<noteq> 0))"
instance ..
end



context update_sem_init begin
lemmas corres_if = corres_if_base[where bool_val' = boolean_C,
                     OF _ _ val_rel_bool_t_C_def[THEN meta_eq_to_obj_eq, THEN iffD1]]
end
(* C heap type class *)
class cogent_C_heap = cogent_C_val +
  fixes is_valid    :: "lifted_globals \<Rightarrow> 'a ptr \<Rightarrow> bool"
  fixes heap        :: "lifted_globals \<Rightarrow> 'a ptr \<Rightarrow> 'a"


(* Non generated stuff *)

(* TODO: move this lemma in the C-parser library, where t1_C_updupd_same
is generated (c-parser/recursive_records/recursive_record_package.ML)
*)
lemma heap_t1_C_update_comp[simp]:
  " heap_t1_C_update f o heap_t1_C_update f' = heap_t1_C_update (f o f')"
  by fastforce


ML 
\<open>
local
  val filename = "onefield_bits_dargentisa.c"
in
val uvals = read_table filename @{theory}
val g = get_callgraph @{theory} filename : callgraph
val heap_info = (Symtab.lookup (HeapInfo.get @{theory}) 
filename |> the  |> #heap_info)
end
\<close>

context onefield_bits_dargentisa begin

(* Unfold the definition of C getters and setters *)

local_setup \<open>generate_isa_getset_records g heap_info uvals  \<close>


lemma get_set_aa[GetSetSimp] : "deref_d2_get_aa (deref_d5_set_aa b v) = v"
  apply(simp add:deref_d2_get_aa_def deref_d5_set_aa_def)
  apply(cases v)
  apply simp
  by word_bitwise

(* Getter/Setter relate to their C counterparts *)


lemma d2_get_aa'_def_alt[GetSetSimp] : "d2_get_aa' x' = do _ <- guard (\<lambda>s. is_valid_t1_C s x');
                                         gets (\<lambda>s. deref_d2_get_aa (heap_t1_C s x')) 
                                      od"
  apply(simp add:d2_get_aa'_def' deref_d2_get_aa_def)  
  by monad_eq

lemma d5_set_aa'_def_alt[GetSetSimp] :
"d5_set_aa' ptr v = (do _ <- guard (\<lambda>s. is_valid_t1_C s ptr);
        modify (heap_t1_C_update (\<lambda>a. a(ptr := deref_d5_set_aa (a ptr) v))) od )
" 
  apply(simp add:deref_d5_set_aa_def d5_set_aa'_def')
  by (monad_eq simp add:comp_def)

end

(* no C counterpart (would be the counterpart of
an unboxed record nested in a record layout: then the 
compiler generate this) 
*)
abbreviation t1_C_aa_type 
   where  "t1_C_aa_type \<equiv> RPrim (Num U32)"

definition t1_C_to_uval :: "t1_C \<Rightarrow> (_,_,_) uval" 
 where t1_C_to_uval_def[GetSetSimp]  :
  "t1_C_to_uval b = URecord [(UPrim (LU32 (onefield_bits_dargentisa.deref_d2_get_aa b)), t1_C_aa_type )]"




(* Typeclass instances *)
instantiation t1_C :: cogent_C_val
begin
definition type_rel_t1_C_def[TypeRelSimp]: "\<And> typ. type_rel typ (_ :: t1_C itself) \<equiv> (typ = RRecord [t1_C_aa_type ])"
definition val_rel_t1_C_def[ValRelSimp]:
    " val_rel uv (x :: t1_C) \<equiv> uv = t1_C_to_uval x "
instance ..
end





(* End of non generated stuff *)

local_setup \<open> local_setup_val_rel_type_rel_put_them_in_buckets "onefield_bits_dargentisa.c" \<close>
local_setup \<open> local_setup_instantiate_cogent_C_heaps_store_them_in_buckets "onefield_bits_dargentisa.c" \<close>
locale Onefield_bits_dargentisa = "onefield_bits_dargentisa" + update_sem_init
begin

(* Relation between program heaps *)
definition
  heap_rel_ptr ::
  "(funtyp, abstyp, ptrtyp) store \<Rightarrow> lifted_globals \<Rightarrow>
   ('a :: cogent_C_heap) ptr \<Rightarrow> bool"
where
  "\<And> \<sigma> h p.
    heap_rel_ptr \<sigma> h p \<equiv>
   (\<forall> uv.
     \<sigma> (ptr_val p) = Some uv \<longrightarrow>
     type_rel (uval_repr uv) TYPE('a) \<longrightarrow>
     is_valid h p \<and> val_rel uv (heap h p))"

lemma heap_rel_ptr_meta:
  "heap_rel_ptr = heap_rel_meta is_valid heap"
  by (simp add: heap_rel_ptr_def[abs_def] heap_rel_meta_def[abs_def])

local_setup \<open> local_setup_heap_rel "onefield_bits_dargentisa.c" \<close>

definition state_rel :: "((funtyp, abstyp, ptrtyp) store \<times> lifted_globals) set"
where
  "state_rel  = {(\<sigma>, h). heap_rel \<sigma> h}"

lemmas val_rel_simps[ValRelSimp] =
  val_rel_word
  val_rel_ptr_def
  val_rel_unit_def
  val_rel_unit_t_C_def
  val_rel_bool_t_C_def
  val_rel_fun_tag

lemmas type_rel_simps[TypeRelSimp] =
  type_rel_word
  type_rel_ptr_def
  type_rel_unit_def
  type_rel_unit_t_C_def
  type_rel_bool_t_C_def


(* Generating the specialised take and put lemmas *)

local_setup \<open> local_setup_take_put_member_case_esac_specialised_lemmas "onefield_bits_dargentisa.c" \<close> 

local_setup \<open> fold tidy_C_fun_def' Cogent_functions \<close>

end (* of locale *)


end
